clone_folder: c:\projects\Crimson


platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release
